---              
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: prod
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-httpd-service
  namespace: prod
spec:
  defaultBackend:
    service:
      name: httpd-service
      port:
        number: 80
  rules:
  - host: pirozhkov-aa.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: prod
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
      - name: nginxn
        image: tabwizard/nginxn:latest
        ports:
        - containerPort: 80
