---
all:
  hosts:
    prod-k8s-control-plane:
      ansible_host: 51.250.13.239
      ip: 192.168.110.3
    prod-k8s-node-1:
      ansible_host: 51.250.21.155
      ip: 192.168.120.5
    prod-k8s-node-2:
      ansible_host: 51.250.38.79
      ip: 192.168.130.19

  vars:
    ansible_user: wizard
    ansible_ssh_private_key_file: /home/wizard/.ssh/yc/yc
    loadbalancer_apiserver:
      address: 51.250.13.239
      port: 6443

  children:
    kube_control_plane:
      hosts:
        prod-k8s-control-plane:
    kube_node:
      hosts:
        prod-k8s-node-1:
        prod-k8s-node-2:
    etcd:
      hosts:
        prod-k8s-control-plane:
        prod-k8s-node-1:
        prod-k8s-node-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
