---
all:
  hosts:
    node1:
      ansible_host: 51.250.93.216
      ip: 192.168.110.12
    node2:
      ansible_host: 51.250.108.144
      ip: 192.168.120.9
    node3:
      ansible_host: 51.250.32.66
      ip: 192.168.130.27

  vars:
    ansible_user: wizard
    ansible_ssh_private_key_file: /home/wizard/.ssh/yc/yc
    loadbalancer_apiserver:
      address: 51.250.93.216
      port: 6443

  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
