---
all:
  hosts:
    k8s-control-plane:
      ansible_host: 51.250.78.57
      ip: 192.168.10.7
    k8s-node-1:
      ansible_host: 51.250.104.203
      ip: 192.168.20.20
    k8s-node-2:
      ansible_host: 51.250.44.27
      ip: 192.168.30.29

  vars:
    ansible_user: wizard
    ansible_ssh_private_key_file: /home/wizard/.ssh/yc/yc
    loadbalancer_apiserver:
      address: 51.250.78.57
      port: 6443

  children:
    kube_control_plane:
      hosts:
        k8s-control-plane:
    kube_node:
      hosts:
        k8s-node-1:
        k8s-node-2:
    etcd:
      hosts:
        k8s-control-plane:
        k8s-node-1:
        k8s-node-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
